export const INIT_SIMULATION = "INIT_SIMULATION";
export const START_SIMULATION = "START_SIMULATION";
export const SET_SIM = "SET_SIM";

export const TIME_TICK = "TIME_TICK";
export const SET_TIMER = "SET_TIMER";
export const STOP_TIMER = "STOP_TIMER";

//WORKSTATION ACTION TYPES
export const SET_WORKSTATION_CONTROL = "SET_WORKSTATION_CONTROL";
export const SETUP_WORKSTATION = "SETUP_WORKSTATION";
export const ASSIGN_RESOURCES = "ASSIGN_RESOURCES";
